using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Arcturus.SmartEnums.CodeGenerator;

[Generator]
public sealed class SmartEnumGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName =
        "Arcturus.SmartEnums.SmartEnumAttribute";

    public void Initialize(
        IncrementalGeneratorInitializationContext context)
    {
        // Inject the attribute into the consuming project.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(
                "SmartEnumAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8));
        });

        var declarations =
            context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) =>
                    node is RecordDeclarationSyntax
                    or ClassDeclarationSyntax,
                static (ctx, cancellationToken) =>
                    CreateModel(ctx, cancellationToken))
            .Where(static model => model is not null);

        context.RegisterSourceOutput(
            declarations,
            static (spc, model) =>
            {
                if (model is null)
                    return;

                var source = Generate(model);

                spc.AddSource(
                    $"{model.HintName}.StringEnum.g.cs",
                    SourceText.From(source, Encoding.UTF8));
            });
    }

    private static StringEnumModel? CreateModel(
        GeneratorAttributeSyntaxContext context,
        CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var attribute = context.Attributes[0];

        var values =
            attribute.ConstructorArguments
                .SelectMany(static argument =>
                {
                    if (argument.Kind == TypedConstantKind.Array)
                        return argument.Values;

                    return ImmutableArray.Create(argument);
                })
                .Where(static x => x.Value is string)
                .Select(static x => (string)x.Value!)
                .Select(ParseValue)
                .ToImmutableArray();

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return new StringEnumModel(
            Namespace: ns,
            TypeName: typeSymbol.Name,
            Accessibility: GetAccessibility(typeSymbol.DeclaredAccessibility),
            IsRecord: typeSymbol.IsRecord,
            Values: values);
    }

    private static StringEnumValue ParseValue(string input)
    {
        var separator = input.IndexOf('=');

        if (separator < 0)
        {
            return new StringEnumValue(
                MemberName: input,
                SerializedValue: input);
        }

        var memberName = input[..separator].Trim();
        var serializedValue = input[(separator + 1)..].Trim();

        return new StringEnumValue(
            memberName,
            serializedValue);
    }

    private static string Generate(StringEnumModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Arcturus.SmartEnums;");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.Append("namespace ")
                .Append(model.Namespace)
                .AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine(
            $"[JsonConverter(typeof(SmartEnumJsonConverter<{model.TypeName}>))]");

        sb.Append(model.Accessibility)
            .Append(" sealed partial ")
            .Append(model.IsRecord ? "record " : "class ")
            .Append(model.TypeName)
            .Append(" : SmartEnum<")
            .Append(model.TypeName)
            .Append(">, ISmartEnum<")
            .Append(model.TypeName)
            .AppendLine(">");
        sb.AppendLine("{");

        foreach (var value in model.Values)
        {
            sb.Append("    public static ")
                .Append(model.TypeName)
                .Append(' ')
                .Append(value.MemberName)
                .Append(" { get; } = new(")
                .Append(ToLiteral(value.SerializedValue))
                .AppendLine(");");
        }

        sb.AppendLine();

        sb.Append("    private ")
            .Append(model.TypeName)
            .AppendLine("(string value)");
        sb.AppendLine("        : base(value)");
        sb.AppendLine("    {");
        sb.AppendLine("    }");

        sb.AppendLine();

        sb.Append("    public static IReadOnlyList<")
            .Append(model.TypeName)
            .AppendLine("> Values { get; } =");
        sb.AppendLine("        new[]");
        sb.AppendLine("        {");

        foreach (var value in model.Values)
        {
            sb.Append("            ")
                .Append(value.MemberName)
                .AppendLine(",");
        }

        sb.AppendLine("        };");

        sb.AppendLine();

        sb.Append("    public static ")
            .Append(model.TypeName)
            .AppendLine(" FromValue(string value)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
        sb.AppendLine();
        sb.AppendLine("        return value switch");
        sb.AppendLine("        {");

        foreach (var value in model.Values)
        {
            sb.Append("            ")
                .Append(ToLiteral(value.SerializedValue))
                .Append(" => ")
                .Append(value.MemberName)
                .AppendLine(",");
        }

        sb.AppendLine(
            $"            _ => throw new ArgumentOutOfRangeException(nameof(value), value, \"Unknown {model.TypeName} value.\")");

        sb.AppendLine("        };");
        sb.AppendLine("    }");

        sb.AppendLine();

        sb.Append("    public static bool TryFromValue(")
            .AppendLine("string value,");
        sb.Append("        out ")
            .Append(model.TypeName)
            .AppendLine("? result)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (value)");
        sb.AppendLine("        {");

        foreach (var value in model.Values)
        {
            sb.Append("            case ")
                .Append(ToLiteral(value.SerializedValue))
                .AppendLine(":");
            sb.Append("                result = ")
                .Append(value.MemberName)
                .AppendLine(";");
            sb.AppendLine("                return true;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                result = null;");
        sb.AppendLine("                return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToLiteral(string value)
    {
        return SymbolDisplay.FormatLiteral(
            value,
            quote: true);
    }

    private static string GetAccessibility(
        Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal"
        };
    }

    private const string AttributeSource =
        """
        // <auto-generated />
        #nullable enable

        namespace Arcturus.SmartEnums;

        [global::System.AttributeUsage(
            global::System.AttributeTargets.Class,
            AllowMultiple = false,
            Inherited = false)]
        internal sealed class SmartEnumAttribute
            : global::System.Attribute
        {
            public SmartEnumAttribute(params string[] values)
            {
                Values = values;
            }

            public string[] Values { get; }
        }
        """;
}

internal sealed record SmartEnumModel(
    string? Namespace,
    string TypeName,
    string Accessibility,
    bool IsRecord,
    ImmutableArray<SmartEnumValue> Values)
{
    public string HintName =>
        Namespace is null
            ? TypeName
            : Namespace.Replace('.', '_') + "_" + TypeName;
}

internal sealed record SmartEnumValue(
    string MemberName,
    string SerializedValue);