<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Arcturus.SmartEnums</PackageId>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>enums,smartenums,arcturus</PackageTags>
		<PackageIcon>nuget.png</PackageIcon>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Description>SmartEnums for Arcturus</Description>
	</PropertyGroup>


	<Target Name="IncludeXmlDocsInPackage" AfterTargets="Build">
		<ItemGroup Condition="Exists('$(OutputPath)$(AssemblyName).xml')">
			<None Include="$(OutputPath)$(AssemblyName).xml" Pack="true" PackagePath="lib\$(TargetFramework)" />
		</ItemGroup>
	</Target>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="..\..\assets\nuget.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<!-- Include the generator as an analyzer in the NuGet package -->
		<None Include="$(OutputPath)\..\..\..\Arcturus.SmartEnums.CodeGenerator\$(Configuration)\netstandard2.0\Arcturus.SmartEnums.CodeGenerator.dll" 
			  Pack="true" 
			  PackagePath="analyzers/dotnet/cs" 
			  Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<!-- Reference generator at build time -->
		<ProjectReference Include="..\Arcturus.SmartEnums.CodeGenerator\Arcturus.SmartEnums.CodeGenerator.csproj" 
						  OutputItemType="Analyzer" 
						  ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
	</ItemGroup>


</Project>
