<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Arcturus.AspNetCore.StandardResponse</PackageId>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageTags>result,resultobject,aspnetcore,arcturus</PackageTags>
		<PackageIconUrl>https://raw.githubusercontent.com/cloudfy/Arcturus/326c991dfe0e024c0c104bde12d3aa91f0a18589/assets/logo_rounded_png.png</PackageIconUrl>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageIcon>nuget.png</PackageIcon>
		<Description>
			Arcturus.AspNetCore.StandardResponse adds support for default response handling.
		</Description>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<Target Name="IncludeXmlDocsInPackage" AfterTargets="Build">
		<ItemGroup Condition="Exists('$(OutputPath)$(AssemblyName).xml')">
			<None Include="$(OutputPath)$(AssemblyName).xml" Pack="true" PackagePath="lib\$(TargetFramework)" />
		</ItemGroup>
	</Target>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>


	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="..\..\assets\nuget.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.301" />
	</ItemGroup>


</Project>
