using Microsoft.CodeAnalysis;
using System.Text;

[Generator]
public class ProjectMetadataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Extract version from MSBuild properties
        var versionProvider = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.Version", out var version);
                provider.GlobalOptions.TryGetValue("build_property.AssemblyVersion", out var assemblyVersion);
                provider.GlobalOptions.TryGetValue("build_property.PackageVersion", out var packageVersion);

                return version ?? assemblyVersion ?? packageVersion ?? "1.0.0";
            });

        var projectRefsFile = context.AdditionalTextsProvider
            .Where(static file => string.Equals(Path.GetFileName(file.Path), "ProjectReferences.txt", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, ct) => file.GetText(ct)?.ToString() ?? "");

        // Combine the two providers
        var combined = projectRefsFile.Combine(versionProvider);

        context.RegisterSourceOutput(combined, static (spc, data) => Generate(spc, data.Left, data.Right));
    }

    private static void Generate(SourceProductionContext context, string content, string version)
    {
        if (string.IsNullOrWhiteSpace(content)) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>\n");
        sb.AppendLine("namespace Projects;");
        sb.AppendLine();
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"Arcturus.DevHost.SourceGenerator\", \"{version}\")]");
        sb.AppendLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = \"Generated code.\")]");

        foreach (var line in content.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries))
        {
            var parts = line.Split('\t');
            if (parts.Length < 3) continue;
            var typeName = FormatName(parts[1].Trim());
            var projectPath = parts[2].Trim().Replace("\\", "\\\\").Replace("\"", "\\\"");

            sb.AppendLine($"public class {typeName} : global::Arcturus.DevHost.Hosting.Abstracts.IProjectMetadata");
            sb.AppendLine("{");
            sb.AppendLine($"    public string ProjectPath => \"{projectPath}\";");
            sb.AppendLine($"    public string ProjectName => \"{typeName}\";");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        context.AddSource("Projects.g.cs", sb.ToString());
    }

    private static string FormatName(string name)
    {
        name = name.Replace(" ", "_").Replace(".", "_").Replace("-", "_");
        if (char.IsDigit(name[0]))
        {
            name = "_" + name;
        }
        return name;
    }
}